github:
  protected_branches:
    main:
      required_status_checks:
        # contexts are the names of checks that must pass
        contexts:
          - build
          - dependency-submission
          - dependency-review
